version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    image: python:3.9-slim-bullseye
    restart: always
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./flask/code:/app
      - ./flask/requirements.txt:/app/requirements.txt
    command: sh -c "pip3 install --no-cache-dir -r requirements.txt && python app.py"
    ports:
      - "5001:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
