version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - custom_connection

  web:
    build: .
    image: python:3.9-slim-bullseye
    restart: always
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./flask/code:/app
      - ./flask/requirements.txt:/app/requirements.txt
    ports:
      - "5001:5000"
    networks:
      - custom_connection

networks:
  custom_connection:
    driver: bridge
